name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for NPM
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Fix package.json bin paths
        run: npm pkg fix

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Publish to NPM
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          VERSION_EXISTS=$(npm view react-native-device-runner@$PACKAGE_VERSION version || echo '')

          if [ -z "$VERSION_EXISTS" ]; then
            echo "Publishing version $PACKAGE_VERSION to NPM..."
            npm publish --access public
          else
            echo "Version $PACKAGE_VERSION already exists in NPM registry. Skipping publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@kdn0325"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Fix package.json bin paths
        run: npm pkg fix

      - name: Configure GitHub Packages authentication
        run: |
          echo "@kdn0325:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Publish to GitHub Packages
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Publishing version $PACKAGE_VERSION to GitHub Packages..."
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
