name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for NPM
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          VERSION_EXISTS=$(npm view react-native-device-runner@$PACKAGE_VERSION version || echo '')

          if [ -z "$VERSION_EXISTS" ]; then
            echo "Publishing version $PACKAGE_VERSION to NPM..."
            npm publish --access public
          else
            echo "Version $PACKAGE_VERSION already exists in NPM registry. Skipping publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@kdn0325"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to GitHub Packages
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Publishing version $PACKAGE_VERSION to GitHub Packages..."
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
